version: '3'

services:
  postgresql:
    container_name: surfspot-postgres
    image: postgres
    # image: postgis/postgis  # Another option
    ports:
      - "5444:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./src/db/sql:/docker-entrypoint-initdb.d
      - surfspot-postgres:/var/lib/postgresql/data

  memcached:
    image: memcached
    ports:
      - "11211:11211"

volumes:
  surfspot-postgres:
